"""Source adapter for Pinia Colada documentation.

Handles Pinia Colada-specific concerns:
  - Standard VitePress layout under ``docs/`` with sidebar in
    ``.vitepress/config/index.ts`` (split-config form, ``'/'`` catch-all key).
  - Heavy TwoSlash usage in code fences: ``// ---cut-start---`` /
    ``---cut-end---`` / ``---cut-before---`` markers, ``// @errors``,
    ``// @filename`` and similar TwoSlash directives, ``// ^?`` hover
    queries, and the ``twoslash`` language tag on the fence opening.
  - ``<HomeSponsors>``, ``<HomeSponsorsGroup>``, ``<FeaturePluginOptions>``,
    ``<PiniaColadaProdDevtools>`` custom components in markdown.
  - ``<script setup>`` blocks (fence-aware stripping).
  - Skips the homepage (``index.md``), ``public/``, ``code-snippets/``,
    ``twoslash/`` helpers, and the auto-generated ``api/`` folder when
    present (TypeDoc output is regenerated by their own build step).
"""

import re
from pathlib import Path

from vue_docs_core.models.entity import ApiEntity
from vue_docs_core.parsing.extractors.pinia_colada import PiniaColadaEntityExtractor

# Files and directories to exclude from ingestion.
_EXCLUDED_DIRS = frozenset(
    {".vitepress", "node_modules", "public", "code-snippets", "twoslash", "api"}
)
_EXCLUDED_ROOT_FILES = frozenset({"index.md"})

# Promotional / demo Vue components in markdown — block + self-closing forms.
_CUSTOM_COMPONENTS = (
    "HomeSponsors",
    "HomeSponsorsGroup",
    "FeaturePluginOptions",
    "PiniaColadaProdDevtools",
    "PiniaColadaDevtools",
)
_COMPONENT_NAMES_RE = "|".join(_CUSTOM_COMPONENTS)
_VUE_COMPONENT_BLOCK_RE = re.compile(
    rf"<(?:{_COMPONENT_NAMES_RE})\b[^>]*>.*?</(?:{_COMPONENT_NAMES_RE})>",
    re.DOTALL,
)
_VUE_COMPONENT_SELF_RE = re.compile(
    rf"^\s*<(?:{_COMPONENT_NAMES_RE})\b(?:\s[^>]*)?\s*/?\s*>\s*$",
    re.MULTILINE,
)

# <script setup> open/close patterns for fence-aware stripping.
_SCRIPT_SETUP_OPEN_RE = re.compile(r"^<script\s+setup\b[^>]*>\s*$")
_SCRIPT_CLOSE_RE = re.compile(r"^</script>\s*$")

# TwoSlash markers — applied only inside code fences.
_CUT_START_RE = re.compile(r"^\s*//\s*---cut-start---\s*$")
_CUT_END_RE = re.compile(r"^\s*//\s*---cut-end---\s*$")
_CUT_BEFORE_RE = re.compile(r"^\s*//\s*---cut-before---\s*$")
_CUT_AFTER_RE = re.compile(r"^\s*//\s*---cut-after---\s*$")
# TwoSlash directives like ``// @errors: 2344`` or ``// @filename: foo.ts``.
# These are build-time hints, not part of the displayed code.
_TWOSLASH_DIRECTIVE_RE = re.compile(
    r"^\s*//\s*@(errors|noErrors|include|filename|module|moduleResolution|"
    r"target|lib|noEmit|noImplicitAny|strict|jsx|esModuleInterop|allowJs|"
    r"checkJs|skipLibCheck)\b.*$"
)
# Hover query lines like ``//       ^?`` or ``//   ^|`` — only meaningful in
# the rendered TwoSlash hover popup, noise in plain text.
_TWOSLASH_QUERY_RE = re.compile(r"^\s*//\s*\^[?|]\s*$")


class PiniaColadaAdapter:
    """Source adapter for Pinia Colada documentation."""

    def post_clone(self, repo_root: Path) -> None:
        """No post-clone steps. TypeDoc generation is intentionally skipped
        — running it pulls the entire ``pnpm install`` tree plus the
        typedoc-vitepress-theme plugin chain, for a marginal coverage gain
        over the curated seed list in the entity extractor."""

    def discover_files(self, docs_path: Path) -> list[Path]:
        """Find all markdown files, excluding the homepage, the auto-
        generated API folder (only present after TypeDoc), and helpers."""
        files: list[Path] = []
        for md_file in sorted(docs_path.rglob("*.md")):
            rel = md_file.relative_to(docs_path)
            parts = rel.parts

            if parts[0] in _EXCLUDED_DIRS:
                continue
            if len(parts) == 1 and parts[0] in _EXCLUDED_ROOT_FILES:
                continue

            files.append(md_file)
        return files

    def parse_sort_keys(self, repo_root: Path) -> dict[str, str]:
        """Parse ``docs/.vitepress/config/index.ts`` to derive sort keys.

        The shared parser handles the ``'/'`` catch-all section key and
        ``link: '/foo/bar.html'`` link form used here.
        """
        from vue_docs_core.parsing.sort_keys import parse_sidebar_config

        config_path = repo_root / "docs" / ".vitepress" / "config" / "index.ts"
        if config_path.exists():
            return parse_sidebar_config(config_path)
        return {}

    def clean_content(self, raw: str) -> str:
        """Strip Pinia Colada-specific noise from markdown content.

        Order matters:
          1. Block-form Vue components first (so opening tags don't survive).
          2. Self-closing components on their own line.
          3. ``<script setup>`` blocks (fence-aware).
          4. TwoSlash artifacts inside code fences.
        """
        result = raw
        result = _VUE_COMPONENT_BLOCK_RE.sub("", result)
        result = _VUE_COMPONENT_SELF_RE.sub("", result)
        result = self._strip_script_setup(result)
        result = self._clean_twoslash(result)
        return result

    @staticmethod
    def _strip_script_setup(text: str) -> str:
        """Remove standalone ``<script setup>`` blocks while preserving
        code fences."""
        lines = text.split("\n")
        output: list[str] = []
        in_fence = False
        in_script = False

        for line in lines:
            stripped = line.lstrip()

            if stripped.startswith("```"):
                in_fence = not in_fence
                output.append(line)
                continue

            if not in_fence:
                if not in_script and _SCRIPT_SETUP_OPEN_RE.match(line):
                    in_script = True
                    continue
                if in_script:
                    if _SCRIPT_CLOSE_RE.match(line):
                        in_script = False
                    continue

            output.append(line)

        return "\n".join(output)

    @staticmethod
    def _clean_twoslash(text: str) -> str:
        """Remove TwoSlash artifacts from code fences.

        Inside fences:
          - Drop content between ``// ---cut-start---`` and
            ``// ---cut-end---`` markers (inclusive of the markers).
          - Drop standalone ``// ---cut-before---`` and
            ``// ---cut-after---`` markers.
          - Drop TwoSlash directive lines (``// @errors:``, ``// @filename:``,
            ``// @moduleResolution:``, etc.) — they're build hints, not code.
          - Drop hover query lines (``// ^?``).
        Fence opening lines have any ``twoslash`` language tag stripped so
        the fence reads as plain ``ts``/``vue``.
        """
        lines = text.split("\n")
        output: list[str] = []
        in_fence = False
        in_cut = False

        for line in lines:
            stripped = line.lstrip()

            if stripped.startswith("```"):
                if not in_fence:
                    in_fence = True
                    line = re.sub(r"\btwoslash\b", "", line).rstrip()
                    output.append(line)
                else:
                    in_fence = False
                    in_cut = False
                    output.append(line)
                continue

            if in_fence:
                if _CUT_START_RE.match(line):
                    in_cut = True
                    continue
                if _CUT_END_RE.match(line):
                    in_cut = False
                    continue
                if in_cut:
                    continue
                if _CUT_BEFORE_RE.match(line) or _CUT_AFTER_RE.match(line):
                    continue
                if _TWOSLASH_DIRECTIVE_RE.match(line):
                    continue
                if _TWOSLASH_QUERY_RE.match(line):
                    continue

            output.append(line)

        return "\n".join(output)

    def build_entity_dictionary(self, docs_path: Path) -> dict[str, ApiEntity]:
        return PiniaColadaEntityExtractor().build_dictionary(docs_path)

    def get_import_patterns(self) -> list[re.Pattern]:
        return PiniaColadaEntityExtractor().get_import_patterns()

    @property
    def high_value_folder_pairs(self) -> list[set[str]]:
        # Guide-to-cookbook is the canonical concept-to-recipe jump,
        # guide-to-plugins links extension points, and guide-to-advanced
        # links from common usage to internals.
        return [{"guide", "cookbook"}, {"guide", "plugins"}, {"guide", "advanced"}]
