"""Source adapter for Vue Flow documentation.

Vue Flow's docs live in the main repo at ``docs/src`` and are powered by
VitePress. The sidebar is at ``docs/src/.vitepress/config.mts``.

API reference is generated by TypeDoc into ``docs/src/typedocs/`` at
build time (``pnpm run typedoc:md``); we intentionally skip running it
here — that requires a full pnpm install of the docs workspace plus the
typedoc-plugin-markdown chain. The seed entity dictionary covers the
public surface from the per-package ``index.ts`` files.

Content cleanup:
  - YAML frontmatter
  - Marketing / homepage components: ``<Banner>``, ``<Showcase>``,
    ``<Acknowledgement>``, ``<Features>``, ``<Home>``
  - ``<script setup>`` blocks (icon imports outside code fences)
  - The ``<VueFlow>``, ``<Handle>``, ``<Background>``, ``<Controls>``,
    ``<MiniMap>``, ``<NodeToolbar>``, ``<NodeResizer>`` components are
    Vue Flow's own API and intentionally preserved.
"""

import re
from pathlib import Path

from vue_docs_core.models.entity import ApiEntity
from vue_docs_core.parsing.extractors.vue_flow import VueFlowEntityExtractor

# Folders + meta files to skip relative to ``docs/src``.
_EXCLUDED_DIRS = frozenset({".vitepress", "node_modules", "public", "assets"})
_EXCLUDED_ROOT_FILES = frozenset({"index.md"})

# Marketing / homepage components — block + self-closing forms.
_MARKETING_COMPONENTS = (
    "Banner",
    "Showcase",
    "Acknowledgement",
    "Features",
    "Home",
)
_MK_NAMES = "|".join(_MARKETING_COMPONENTS)
_MK_BLOCK_RE = re.compile(
    rf"<(?:{_MK_NAMES})\b[^>]*>.*?</(?:{_MK_NAMES})>",
    re.DOTALL,
)
_MK_SELF_RE = re.compile(
    rf"^\s*<(?:{_MK_NAMES})\b[^>]*/?>\s*$",
    re.MULTILINE,
)

# <script setup> open/close patterns for fence-aware stripping.
_SCRIPT_SETUP_OPEN_RE = re.compile(r"^<script\s+setup\b[^>]*>\s*$")
_SCRIPT_CLOSE_RE = re.compile(r"^</script>\s*$")

# YAML frontmatter delimiter.
_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


class VueFlowAdapter:
    """Source adapter for Vue Flow documentation."""

    def post_clone(self, repo_root: Path) -> None:
        """No post-clone steps. TypeDoc generation is intentionally skipped
        — it requires the full pnpm install of the docs workspace plus the
        typedoc-plugin-markdown chain. The entity dictionary seeds the
        public API surface directly from the per-package source."""

    def discover_files(self, docs_path: Path) -> list[Path]:
        """Find markdown files under ``docs/src``, excluding the homepage,
        ``.vitepress`` config, and asset folders."""
        files: list[Path] = []
        for md_file in sorted(docs_path.rglob("*.md")):
            rel = md_file.relative_to(docs_path)
            parts = rel.parts

            if parts[0] in _EXCLUDED_DIRS:
                continue
            if any(p.startswith(".") for p in parts[:-1]):
                continue
            if len(parts) == 1 and parts[0] in _EXCLUDED_ROOT_FILES:
                continue

            files.append(md_file)
        return files

    def parse_sort_keys(self, repo_root: Path) -> dict[str, str]:
        """Parse the VitePress sidebar at ``docs/src/.vitepress/config.mts``."""
        from vue_docs_core.parsing.sort_keys import parse_sidebar_config

        config_path = repo_root / "docs" / "src" / ".vitepress" / "config.mts"
        if config_path.exists():
            return parse_sidebar_config(config_path)
        return {}

    def clean_content(self, raw: str) -> str:
        """Strip frontmatter, marketing components, and ``<script setup>`` blocks."""
        result = raw

        # 1. YAML frontmatter.
        result = _FRONTMATTER_RE.sub("", result, count=1)

        # 2. Marketing components (block + self-closing).
        result = _MK_BLOCK_RE.sub("", result)
        result = _MK_SELF_RE.sub("", result)

        # 3. ``<script setup>`` blocks outside code fences.
        result = self._strip_script_setup(result)

        return result

    @staticmethod
    def _strip_script_setup(text: str) -> str:
        """Remove standalone ``<script setup>`` blocks while preserving code fences."""
        lines = text.split("\n")
        output: list[str] = []
        in_fence = False
        in_script = False

        for line in lines:
            stripped = line.lstrip()

            if stripped.startswith("```"):
                in_fence = not in_fence
                output.append(line)
                continue

            if not in_fence:
                if not in_script and _SCRIPT_SETUP_OPEN_RE.match(line):
                    in_script = True
                    continue
                if in_script:
                    if _SCRIPT_CLOSE_RE.match(line):
                        in_script = False
                    continue

            output.append(line)

        return "\n".join(output)

    def build_entity_dictionary(self, docs_path: Path) -> dict[str, ApiEntity]:
        return VueFlowEntityExtractor().build_dictionary(docs_path)

    def get_import_patterns(self) -> list[re.Pattern]:
        return VueFlowEntityExtractor().get_import_patterns()

    @property
    def high_value_folder_pairs(self) -> list[set[str]]:
        # Guide-to-examples is the canonical concept-to-recipe jump.
        # Guide-to-typedocs links concepts to API reference (when generated).
        return [{"guide", "examples"}, {"guide", "typedocs"}]
